[build]
  command = "npm run build"
  publish = "dist/"

[[redirects]]
  from = "/login"
  to = "/app/login"
  status = 301
  force = true

[[redirects]]
  from = "/dashboard"
  to = "/app/dashboard"
  status = 301
  force = true

[[headers]]
  for = "/fonts/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
